"""
Connect an xml document to a python object
"""
__author__ = "Angelo Galleja"
__copyright__ = "Copyright 2017, Angelo Galleja"
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "Angelo Galleja"
__email__ = "angelo.galleja@intco.it"
__status__ = "Production"
